# Generated by Django 3.0.5 on 2020-04-12 00:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('state', models.CharField(choices=[('processing', 'First time processing'), ('correcting', 'Unfinished correction'), ('error', 'In error'), ('resolved', 'Processing resolved')], default='processing', help_text='The state of the payment', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], help_text='The status of the transaction', max_length=32)),
                ('location', models.CharField(choices=[('origination_bank', 'Origination Bank'), ('routable', 'Routable'), ('destination_bank', 'Destination Bank')], help_text='The location of the transaction', max_length=32)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Item', verbose_name='The transactions payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
